"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Contracts = void 0;
var Contracts;
(function (Contracts) {
    Contracts["GasContractName"] = "gas";
    Contracts["BlockContractName"] = "block";
    Contracts["StakeContractName"] = "stake";
    Contracts["SwapContractName"] = "swap";
    Contracts["AccountContractName"] = "account";
    Contracts["ConsensusContractName"] = "consensus";
    Contracts["GovernanceContractName"] = "governance";
    Contracts["StorageContractName"] = "storage";
    Contracts["ValidatorContractName"] = "validator";
    Contracts["InteropContractName"] = "interop";
    Contracts["ExchangeContractName"] = "exchange";
    Contracts["PrivacyContractName"] = "privacy";
    Contracts["RelayContractName"] = "relay";
    Contracts["RankingContractName"] = "ranking";
})(Contracts = exports.Contracts || (exports.Contracts = {}));
