"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NativeContractKind = void 0;
var NativeContractKind;
(function (NativeContractKind) {
    NativeContractKind[NativeContractKind["Gas"] = 0] = "Gas";
    NativeContractKind[NativeContractKind["Block"] = 1] = "Block";
    NativeContractKind[NativeContractKind["Stake"] = 2] = "Stake";
    NativeContractKind[NativeContractKind["Swap"] = 3] = "Swap";
    NativeContractKind[NativeContractKind["Account"] = 4] = "Account";
    NativeContractKind[NativeContractKind["Consensus"] = 5] = "Consensus";
    NativeContractKind[NativeContractKind["Governance"] = 6] = "Governance";
    NativeContractKind[NativeContractKind["Storage"] = 7] = "Storage";
    NativeContractKind[NativeContractKind["Validator"] = 8] = "Validator";
    NativeContractKind[NativeContractKind["Interop"] = 9] = "Interop";
    NativeContractKind[NativeContractKind["Exchange"] = 10] = "Exchange";
    NativeContractKind[NativeContractKind["Privacy"] = 11] = "Privacy";
    NativeContractKind[NativeContractKind["Relay"] = 12] = "Relay";
    NativeContractKind[NativeContractKind["Ranking"] = 13] = "Ranking";
    NativeContractKind[NativeContractKind["Market"] = 14] = "Market";
    NativeContractKind[NativeContractKind["Friends"] = 15] = "Friends";
    NativeContractKind[NativeContractKind["Mail"] = 16] = "Mail";
    NativeContractKind[NativeContractKind["Sale"] = 17] = "Sale";
    NativeContractKind[NativeContractKind["Unknown"] = 18] = "Unknown";
})(NativeContractKind = exports.NativeContractKind || (exports.NativeContractKind = {}));
